catalog:
  "@tanstack/react-query": "^5.90.1"
  "@types/node": "^22.15.32"
  "@types/react": "^19.1"
  "@types/react-dom": "^19.1"
  "@typescript/native-preview": "7.0.0-dev.20251025.1"
  "@wagmi/core": "^2.21.2"
  ox: "^0.9.6"
  prool: "^0.0.23"
  react: "^19.1"
  react-dom: "^19.1"
  typescript: "~5.9.2"
  viem: "^2.43.3"
  vite: "^6.4.1"
  vitest: "^4.0.3"
  wagmi: "^2.18.2"
packages:
  - "."
